### ISSUE TITLE
thank you - would you mind adding a basic guide? 

### ISSUE THREAD

**Issue by sezbez** [billmcilhargey/docker-gunbot#1]
I'd love to use this as It seems to pull everythign you need. where as magicdude4evas version requires you to build the folder structure first which isn't in their instructions?

**Comment by billmcilhargey** [comment]
Will do!  I'm actually getting ready to do a major upgrade and guide here really soon. Thanks for the reply!

**Comment by billmcilhargey** [comment]
added basic guide @sezbez
