### ISSUE TITLE
Issues when using Docker Run command with the port -p flag.

### ISSUE THREAD

**Issue by TechDefense** [billmcilhargey/docker-gunbot#8]
Seems like a recent update caused some issues when running the port -p flag. Docker fails to run.

It was working fine 2-days ago, I've tested with other images and they pull fine with the -p flag

*I have tested this on Ubuntu lts:latest and on windows 11 and get the same exact error.

Here is the command and error output:
C:\Users>docker run -d computeronix/gunbot:stable-25.0.8 -p 5010:5000
Unable to find image 'computeronix/gunbot:stable-25.0.8' locally
stable-25.0.8: Pulling from computeronix/gunbot
45c04dd46fbf: Pull complete
efed4205960f: Pull complete
4f4fb700ef54: Pull complete
27047ddfec81: Pull complete
Digest: sha256:6b71359b917e6903532a29297f266abe1cc22c231c70ba71308dfe9be4814fd9
Status: Downloaded newer image for computeronix/gunbot:stable-25.0.8
7f5b6195f4482d427c152d3724ce5596d24279f8dce703ff8a9b26615403a951
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "-p": executable file not found in $PATH: unknown.

C:\Users>docker run -d computeronix/gunbot:beta-25.1.7 -p 5000:5000
Unable to find image 'computeronix/gunbot:beta-25.1.7' locally
beta-25.1.7: Pulling from computeronix/gunbot
45c04dd46fbf: Already exists
3fb252d06139: Pull complete
4f4fb700ef54: Pull complete
fcaef8ecff70: Pull complete
Digest: sha256:f924a6d096454525bd3c5cf2d0cc0deb19f7e678ab859f764df6787aab3c6d22
Status: Downloaded newer image for computeronix/gunbot:beta-25.1.7
60a47fd82b0cf95b69ae7b789d93b52f4b21a73a39333d976289807ce8cdcc64
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "-p": executable file not found in $PATH: unknown.

--
user@user:~$ sudo docker run -d computeronix/gunbot:latest -p 5010:5000
1bfa0be45596e711c559f6a366a2280a1f72f0176b787e3a76d15bd9d16415e6
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "-p": executable file not found in $PATH: unknown.

user@user:~$ sudo docker run -d computeronix/gunbot:latest -publish 5010:5000
0348f4b9780660cd46d297f65cd38dcb7e7bf211524f5c6da8d00d148b2cad33
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "-publish": executable file not found in $PATH: unknown.

**Comment by billmcilhargey** [comment]
Don't put -p at the end of the run command

incorrect:
docker run -d computeronix/gunbot:stable-25.0.8 -p 5010:5000

correct:
docker run -d -p 5010:5000 computeronix/gunbot:stable-25.0.8

thank you for reporting -- all docs have now been updated
